const mongoose = require('mongoose');

const MatchDetails = mongoose.model('matchdetails', {
	matchId: String,
	gameCreation: Number,
	gameDuration: Number,
	gameMode: String,
	gameType: String,
	assists: Number,
	kills: Number,
	role: String,
	champLevel: Number,
	championId: Number,
	championName: String,
	deaths: Number,
	item0: Number,
	item1: Number,
	item2: Number,
	item3: Number,
	item4: Number,
	item5: Number,
	item6: Number,
	summoner1Id: Number,
	summoner2Id: Number,
	summonerId: String,
	summonerLevel: Number,
	summonerName: String,
	totalDamageDealtToChampions: Number,
	teamId: Number,
    teamPosition: String,
	totalMinionsKilled: Number,
	killParticipation: Number,
	kda: Number,
    primaryRune: Number,
    secondaryRune: Number,
    championId: Number,
    baronKills: Number,
    dragonKills: Number,
    riftHeraldKills: Number,
    inhibitorKills: Number,
    towerKills: Number,
    win: Boolean,
});

module.exports = MatchDetails;
